use crate::android::backend::wayland::{
    input::{
        RelativePosition, WinitInput, WinitKeyboardInputEvent, WinitMouseInputEvent,
        WinitMouseMovedEvent, WinitMouseWheelEvent, WinitTouchCancelledEvent, WinitTouchEndedEvent,
        WinitTouchMovedEvent, WinitTouchStartedEvent,
    },
    keymap::physicalkey_to_scancode,
    TouchMode, WaylandBackend,
};
use crate::android::utils::ndk;
use smithay::backend::input::InputEvent;
use smithay::utils::{Physical, Size};
use winit::dpi::PhysicalPosition;
use winit::event::{ElementState, MouseScrollDelta, Touch, TouchPhase, WindowEvent};

/// Specific events generated by Winit
#[derive(Debug)]
pub enum CentralizedEvent {
    /// The window has been resized
    Resized {
        /// The new physical size (in pixels)
        size: Size<i32, Physical>,
        guest_scale_factor: f64,
    },

    /// The focus state of the window changed
    Focus(bool),

    /// An input event occurred.
    Input(InputEvent<WinitInput>),

    /// The user requested to close the window.
    CloseRequested,

    /// A redraw was requested
    Redraw,

    /// TODO: Support these events
    Unsupported,
}

fn reconcile_modifiers(meta_state: u32, time: u32, backend: &mut WaylandBackend) {
    const AMETA_ALT_ON: u32 = 0x02;
    const AMETA_ALT_LEFT_ON: u32 = 0x10;
    const AMETA_ALT_RIGHT_ON: u32 = 0x20;
    const AMETA_SHIFT_ON: u32 = 0x01;
    const AMETA_SHIFT_LEFT_ON: u32 = 0x40;
    const AMETA_SHIFT_RIGHT_ON: u32 = 0x80;
    const AMETA_CTRL_ON: u32 = 0x1000;
    const AMETA_CTRL_LEFT_ON: u32 = 0x2000;
    const AMETA_CTRL_RIGHT_ON: u32 = 0x4000;
    const AMETA_META_ON: u32 = 0x10000;
    const AMETA_META_LEFT_ON: u32 = 0x20000;
    const AMETA_META_RIGHT_ON: u32 = 0x40000;

    const KEY_LEFTALT: u32 = 56;
    const KEY_RIGHTALT: u32 = 100;
    const KEY_LEFTSHIFT: u32 = 42;
    const KEY_RIGHTSHIFT: u32 = 54;
    const KEY_LEFTCTRL: u32 = 29;
    const KEY_RIGHTCTRL: u32 = 97;
    const KEY_LEFTMETA: u32 = 125;
    const KEY_RIGHTMETA: u32 = 126;

    let mut to_release = Vec::new();

    if (meta_state & (AMETA_ALT_ON | AMETA_ALT_LEFT_ON | AMETA_ALT_RIGHT_ON)) == 0 {
        if backend.pressed_keys.contains(&KEY_LEFTALT) {
            to_release.push(KEY_LEFTALT);
        }
        if backend.pressed_keys.contains(&KEY_RIGHTALT) {
            to_release.push(KEY_RIGHTALT);
        }
    }
    if (meta_state & (AMETA_CTRL_ON | AMETA_CTRL_LEFT_ON | AMETA_CTRL_RIGHT_ON)) == 0 {
        if backend.pressed_keys.contains(&KEY_LEFTCTRL) {
            to_release.push(KEY_LEFTCTRL);
        }
        if backend.pressed_keys.contains(&KEY_RIGHTCTRL) {
            to_release.push(KEY_RIGHTCTRL);
        }
    }
    if (meta_state & (AMETA_SHIFT_ON | AMETA_SHIFT_LEFT_ON | AMETA_SHIFT_RIGHT_ON)) == 0 {
        if backend.pressed_keys.contains(&KEY_LEFTSHIFT) {
            to_release.push(KEY_LEFTSHIFT);
        }
        if backend.pressed_keys.contains(&KEY_RIGHTSHIFT) {
            to_release.push(KEY_RIGHTSHIFT);
        }
    }
    if (meta_state & (AMETA_META_ON | AMETA_META_LEFT_ON | AMETA_META_RIGHT_ON)) == 0 {
        if backend.pressed_keys.contains(&KEY_LEFTMETA) {
            to_release.push(KEY_LEFTMETA);
        }
        if backend.pressed_keys.contains(&KEY_RIGHTMETA) {
            to_release.push(KEY_RIGHTMETA);
        }
    }

    for scancode in to_release {
        backend.pressed_keys.remove(&scancode);
        backend.key_counter = backend.key_counter.saturating_sub(1);
        let serial = smithay::utils::SERIAL_COUNTER.next_serial();
        backend.compositor.keyboard.input::<(), _>(
            &mut backend.compositor.state,
            scancode.into(),
            smithay::backend::input::KeyState::Released,
            serial,
            time,
            |_, _, _| smithay::input::keyboard::FilterResult::Forward,
        );
        log::debug!("Reconciled modifier released: scancode={scancode}");
    }
}

fn centralize_keyboard(
    scancode: u32,
    state: ElementState,
    time: u64,
    backend: &mut WaylandBackend,
) -> CentralizedEvent {
    match state {
        ElementState::Pressed => {
            backend.key_counter += 1;
            backend.pressed_keys.insert(scancode);
        }
        ElementState::Released => {
            backend.key_counter = backend.key_counter.saturating_sub(1);
            backend.pressed_keys.remove(&scancode);
        }
    };

    let event = InputEvent::Keyboard {
        event: WinitKeyboardInputEvent {
            time,
            key: scancode,
            count: backend.key_counter,
            state,
        },
    };
    CentralizedEvent::Input(event)
}

pub fn centralize_injected_keyboard(
    scancode: u32,
    state: ElementState,
    time: u64,
    backend: &mut WaylandBackend,
) -> CentralizedEvent {
    centralize_keyboard(scancode, state, time, backend)
}

pub fn centralize(event: WindowEvent, backend: &mut WaylandBackend) -> CentralizedEvent {
    let time = backend.clock.now().as_millis() as u64;
    return match event {
        WindowEvent::Resized(size) => {
            let (w, h): (i32, i32) = size.into();
            backend.guest_scale_factor = ndk::scale_factor(&backend.android_app);

            CentralizedEvent::Resized {
                size: (w, h).into(),
                guest_scale_factor: backend.guest_scale_factor,
            }
        }
        WindowEvent::ScaleFactorChanged { .. } => {
            backend.guest_scale_factor = ndk::scale_factor(&backend.android_app);
            let Some(renderer) = backend.graphic_renderer.as_ref() else {
                return CentralizedEvent::Unsupported;
            };
            let (w, h): (i32, i32) = renderer.window().inner_size().into();
            CentralizedEvent::Resized {
                size: (w, h).into(),
                guest_scale_factor: backend.guest_scale_factor,
            }
        }
        WindowEvent::RedrawRequested => CentralizedEvent::Redraw,
        WindowEvent::CloseRequested => CentralizedEvent::CloseRequested,
        WindowEvent::Focused(focused) => CentralizedEvent::Focus(focused),
        WindowEvent::KeyboardInput {
            event,
            is_synthetic,
            ..
        } if !is_synthetic && !event.repeat => {
            let Some(scancode) = physicalkey_to_scancode(event.physical_key) else {
                // Never forward the sentinel evdev code 0. It is interpreted as an unknown
                // key by libinput/KWin and can leave modifiers or key counters inconsistent.
                log::debug!("Dropping keyboard event without a physical evdev mapping: {event:?}");
                return CentralizedEvent::Unsupported;
            };
            reconcile_modifiers(event.android_meta_state(), time as u32, backend);
            centralize_keyboard(scancode, event.state, time, backend)
        }
        WindowEvent::CursorMoved { position, .. } => {
            // Border (letterbox) moves are outside the guest: drop instead of
            // warping the Plasma cursor to the nearest edge, and remember the
            // outside state so a later click cannot fire at stale coordinates.
            let Some(logical) = physical_to_logical_position(backend, position) else {
                backend
                    .button_tracker
                    .note_motion(false, (position.x, position.y));
                return CentralizedEvent::Unsupported;
            };
            backend
                .button_tracker
                .note_motion(true, (position.x, position.y));
            let event = InputEvent::PointerMotionAbsolute {
                event: WinitMouseMovedEvent {
                    time,
                    position: relative_position(backend, position),
                    global_position: logical,
                    physical_position: position,
                    android_device_id: None,
                    android_source: None,
                    android_tool_type: None,
                },
            };
            CentralizedEvent::Input(event)
        }
        WindowEvent::AndroidPointerMoved {
            position,
            android_device_id,
            source,
            tool_type,
            ..
        } => {
            let Some(logical) = physical_to_logical_position(backend, position) else {
                backend
                    .button_tracker
                    .note_motion(false, (position.x, position.y));
                return CentralizedEvent::Unsupported;
            };
            backend
                .button_tracker
                .note_motion(true, (position.x, position.y));
            CentralizedEvent::Input(InputEvent::PointerMotionAbsolute {
                event: WinitMouseMovedEvent {
                    time,
                    position: relative_position(backend, position),
                    global_position: logical,
                    physical_position: position,
                    android_device_id: Some(android_device_id),
                    android_source: Some(source),
                    android_tool_type: Some(tool_type),
                },
            })
        }
        WindowEvent::MouseWheel { delta, .. } => {
            let event = InputEvent::PointerAxis {
                event: WinitMouseWheelEvent { time, delta },
            };
            CentralizedEvent::Input(event)
        }
        WindowEvent::MouseInput { state, button, .. } => {
            // Mouse button events carry no position: consult the tracked
            // inside/outside state from the last motion. Border presses never
            // reach the guest (no click at stale coordinates); releases land
            // exactly for previously forwarded presses (no stuck buttons).
            use smithay::backend::input::PointerButtonEvent;
            let probe = WinitMouseInputEvent {
                time,
                button,
                state,
                is_x11: false,
            };
            let code = probe.button_code();
            let forward = match state {
                ElementState::Pressed => backend.button_tracker.press(code),
                ElementState::Released => backend.button_tracker.release(code),
            };
            if !forward {
                return CentralizedEvent::Unsupported;
            }
            let event = InputEvent::PointerButton { event: probe };
            CentralizedEvent::Input(event)
        }
        WindowEvent::Touch(Touch {
            phase: TouchPhase::Started,
            location,
            id,
            ..
        }) => {
            // A touch starting in transitional letterbox is outside the guest:
            // suppress the whole gesture (a border press sliding inside must
            // still never click) without disturbing guest gesture state.
            let Some(logical) = physical_to_logical_position(backend, location) else {
                backend.suppressed_touch_ids.insert(id);
                return CentralizedEvent::Unsupported;
            };
            backend.touch_points.insert(id, location);
            backend.scroll_centroid = Some(centroid(&backend.touch_points));

            if backend.touch_points.len() >= 2 {
                // A second finger is unambiguously a scroll, whatever the first one was doing.
                backend.touch_mode = TouchMode::Scroll;
                return CentralizedEvent::Unsupported;
            }

            backend.touch_mode = TouchMode::Undecided;
            backend.touch_down_position = Some(location);
            backend.touch_down_time = Some(time);
            backend.touch_down_generation = Some(
                backend
                    .compositor
                    .state
                    .authoritative_display_state
                    .resize_generation,
            );
            CentralizedEvent::Input(InputEvent::TouchDown {
                event: WinitTouchStartedEvent {
                    time,
                    global_position: logical,
                    position: relative_position(backend, location),
                    id,
                },
            })
        }
        WindowEvent::Touch(Touch {
            phase: TouchPhase::Moved,
            location,
            id,
            ..
        }) => {
            // Suppressed (border-started) touches never affect guest state —
            // not the points, mode, centroid, or slop anchor.
            if backend.suppressed_touch_ids.contains(&id) {
                return CentralizedEvent::Unsupported;
            }
            backend.touch_points.insert(id, location);

            if backend.touch_mode == TouchMode::Undecided && travelled_past_slop(backend, location)
            {
                backend.touch_mode = TouchMode::Scroll;
                // Start scrolling from here, so the slop the finger just used up doesn't
                // arrive as one jump.
                backend.scroll_centroid = Some(centroid(&backend.touch_points));
            }
            if backend.touch_mode == TouchMode::LongPress && travelled_past_slop(backend, location)
            {
                backend.touch_mode = TouchMode::Drag;
            }

            match backend.touch_mode {
                // Still deciding between a tap, a scroll and a long press: don't move the
                // cursor yet, or a scroll would drag it along.
                TouchMode::Undecided | TouchMode::LongPress => CentralizedEvent::Unsupported,
                TouchMode::Scroll => {
                    // Scroll by the centroid delta, which is the finger itself when only one
                    // is down. Positive axis values scroll the view down, so the raw delta
                    // (negated once more in `WinitMouseWheelEvent::amount`) makes the content
                    // follow the finger the way Android does.
                    let new_centroid = centroid(&backend.touch_points);
                    let last = backend.scroll_centroid.replace(new_centroid);
                    let Some(last) = last else {
                        return CentralizedEvent::Unsupported;
                    };
                    let dx = new_centroid.x - last.x;
                    let dy = new_centroid.y - last.y;
                    if dx == 0.0 && dy == 0.0 {
                        return CentralizedEvent::Unsupported;
                    }
                    CentralizedEvent::Input(InputEvent::PointerAxis {
                        event: WinitMouseWheelEvent {
                            time,
                            delta: MouseScrollDelta::PixelDelta(PhysicalPosition { x: dx, y: dy }),
                        },
                    })
                }
                TouchMode::Drag => {
                    // A drag sliding through letterbox is outside the guest for
                    // that segment: drop the move (cursor stays) rather than
                    // clamping to the viewport edge.
                    let Some(logical) = physical_to_logical_position(backend, location) else {
                        return CentralizedEvent::Unsupported;
                    };
                    CentralizedEvent::Input(InputEvent::TouchMotion {
                        event: WinitTouchMovedEvent {
                            time,
                            position: relative_position(backend, location),
                            global_position: logical,
                            id,
                        },
                    })
                }
            }
        }

        WindowEvent::Touch(Touch {
            phase: TouchPhase::Ended,
            location,
            id,
            ..
        }) => {
            if backend.suppressed_touch_ids.remove(&id) {
                // A suppressed gesture ending changes nothing guest-side.
                return CentralizedEvent::Unsupported;
            }
            backend.touch_points.remove(&id);
            if !backend.touch_points.is_empty() {
                // Don't forward a stray TouchUp while other fingers are still down; re-anchor
                // the centroid so the remaining fingers don't jump the scroll.
                backend.scroll_centroid = Some(centroid(&backend.touch_points));
                return CentralizedEvent::Unsupported;
            }

            let mode = backend.touch_mode;
            // Border lift: taps/long-presses must NOT become edge clicks.
            // Scroll/Drag lifts in a border still terminate the gesture, but
            // carry dummy coordinates flagged `in_guest = false`: the handler
            // releases at the current guest location without synthesizing any
            // edge movement.
            let (logical, in_guest) = match physical_to_logical_position(backend, location) {
                Some(logical) => (logical, true),
                None => {
                    if matches!(mode, TouchMode::Scroll | TouchMode::Drag) {
                        (PhysicalPosition::new(0.0, 0.0), false)
                    } else {
                        backend.reset_touch_state();
                        return CentralizedEvent::Unsupported;
                    }
                }
            };
            backend.reset_touch_state();
            CentralizedEvent::Input(InputEvent::TouchUp {
                event: WinitTouchEndedEvent {
                    time,
                    id,
                    mode,
                    x: logical.x,
                    y: logical.y,
                    in_guest,
                },
            })
        }
        WindowEvent::Touch(Touch {
            phase: TouchPhase::Cancelled,
            id,
            ..
        }) => {
            if backend.suppressed_touch_ids.remove(&id) {
                return CentralizedEvent::Unsupported;
            }
            backend.touch_points.remove(&id);
            if !backend.touch_points.is_empty() {
                backend.scroll_centroid = Some(centroid(&backend.touch_points));
                return CentralizedEvent::Unsupported;
            }

            backend.reset_touch_state();
            CentralizedEvent::Input(InputEvent::TouchCancel {
                event: WinitTouchCancelledEvent { time, id },
            })
        }

        _ => {
            log::info!("Unhandled event: {:?}", event);
            CentralizedEvent::Unsupported
        }
    };
}

/// Normalize a window-relative pixel position into the 0..1 range the input backend expects.
///
/// Uses the single authoritative host size from the presentation snapshot —
// never a separate `window.inner_size()` query that could belong to a
/// different resize generation than the coordinate transform used for mapping.
fn relative_position(
    backend: &WaylandBackend,
    location: PhysicalPosition<f64>,
) -> RelativePosition {
    let (host_w, host_h) = backend
        .compositor
        .state
        .authoritative_display_state
        .physical_size;
    RelativePosition::new(
        location.x / host_w.max(1) as f64,
        location.y / host_h.max(1) as f64,
    )
}

/// Convert an Android physical surface position exactly once at the ingestion boundary.
///
/// Uses one coherent presentation snapshot for the operation. Returns `None`
/// for touches/clicks in transitional letterbox borders — they are outside the
/// guest desktop and must NOT be clamped into edge clicks.
fn physical_to_logical_position(
    backend: &WaylandBackend,
    location: PhysicalPosition<f64>,
) -> Option<PhysicalPosition<f64>> {
    let snapshot = backend
        .compositor
        .state
        .authoritative_display_state
        .presentation_snapshot();
    snapshot
        .physical_to_logical(location.x, location.y)
        .map(|(lx, ly)| PhysicalPosition::new(lx, ly))
}

/// Whether the finger has moved far enough from where it landed to stop being a tap.
fn travelled_past_slop(backend: &WaylandBackend, location: PhysicalPosition<f64>) -> bool {
    backend
        .touch_down_position
        .map(|start| {
            let dx = location.x - start.x;
            let dy = location.y - start.y;
            dx * dx + dy * dy > backend.touch_slop_px * backend.touch_slop_px
        })
        .unwrap_or(false)
}

fn centroid(
    points: &std::collections::HashMap<u64, PhysicalPosition<f64>>,
) -> PhysicalPosition<f64> {
    let n = points.len() as f64;
    let (sx, sy) = points
        .values()
        .fold((0.0, 0.0), |(sx, sy), p| (sx + p.x, sy + p.y));
    PhysicalPosition {
        x: sx / n,
        y: sy / n,
    }
}
